// SQLite access via tauri-plugin-sql (official plugin, see design doc §2.5).
// Migrations are generated by drizzle-kit and bundled via Vite `?raw` imports,
// then executed here — no hand-written SQL management.

import Database from "@tauri-apps/plugin-sql";
import migration0000 from "@/db/migrations/0000_curly_norman_osborn.sql?raw";
import migration0001 from "@/db/migrations/0001_windy_mystique.sql?raw";

const MIGRATIONS: Array<{ id: string; sql: string }> = [
  { id: "0000_curly_norman_osborn", sql: migration0000 },
  { id: "0001_windy_mystique", sql: migration0001 },
];

export const DB_NAME = "sqlite:todolist.db";

let db: Database | null = null;

export function getDb(): Database {
  if (!db) throw new Error("Database not initialized yet");
  return db;
}

export async function initDb(): Promise<void> {
  if (db) return;
  db = await Database.load(DB_NAME);
  await runMigrations();
  await seedDefaults();
}

async function runMigrations(): Promise<void> {
  // Track applied migrations in a tiny meta table.
  await getDb().execute(
    "CREATE TABLE IF NOT EXISTS _migrations (id TEXT PRIMARY KEY, applied_at TEXT DEFAULT (datetime('now')))",
  );
  const rows = (await getDb().select<{ id: string }[]>(
    "SELECT id FROM _migrations",
  )) as unknown as Array<{ id: string }>;
  const applied = new Set(rows.map((r) => r.id));

  for (const m of MIGRATIONS) {
    if (applied.has(m.id)) continue;
    // drizzle-kit emits statements separated by `--> statement-breakpoint`;
    // split on that, then on the trailing `;`, and make DDL idempotent so a
    // partially-applied migration can be retried safely on next launch.
    const statements = m.sql
      .split(/-->\s*statement-breakpoint/)
      .flatMap((chunk) =>
        chunk
          .split(/;\s*(?:\n|$)/)
          .map((s) => s.trim())
          .filter((s) => s.length > 0),
      )
      .map((s) =>
        s
          .replace(/^CREATE TABLE /, "CREATE TABLE IF NOT EXISTS ")
          .replace(/^CREATE (UNIQUE )?INDEX /, "CREATE $1INDEX IF NOT EXISTS "),
      );
    for (const stmt of statements) {
      await getDb().execute(stmt);
    }
    await getDb().execute("INSERT INTO _migrations (id) VALUES ($1)", [m.id]);
  }
}

async function seedDefaults(): Promise<void> {
  const rows = (await getDb().select<{ key: string }[]>(
    "SELECT key FROM settings WHERE key IN ('ai.provider','ai.model','ai.apiKey','ai.baseUrl','autoPlan','notifications','carryOver','lastPlanDate')",
  )) as unknown as Array<{ key: string }>;
  const existing = new Set(rows.map((r) => r.key));
  const defaults: Array<[string, unknown]> = [
    ["ai.provider", "ollama"],
    ["ai.model", "qwen2.5:7b"],
    ["ai.apiKey", ""],
    ["ai.baseUrl", "http://localhost:11434/v1"],
    ["autoPlan", true],
    ["notifications", true],
    ["carryOver", true],
    ["lastPlanDate", ""],
  ];
  for (const [key, value] of defaults) {
    if (!existing.has(key)) {
      await getDb().execute(
        "INSERT INTO settings (key, value) VALUES ($1, $2)",
        [key, JSON.stringify(value)],
      );
    }
  }
}

// ---------------------------------------------------------------------------
// Typed helpers
// ---------------------------------------------------------------------------

export async function getSetting<T>(key: string, fallback: T): Promise<T> {
  const rows = (await getDb().select<{ value: string | null }[]>(
    "SELECT value FROM settings WHERE key = $1",
    [key],
  )) as unknown as Array<{ value: string | null }>;
  if (rows.length === 0 || rows[0].value === null) return fallback;
  try {
    return JSON.parse(rows[0].value) as T;
  } catch {
    return fallback;
  }
}

export async function setSetting(key: string, value: unknown): Promise<void> {
  await getDb().execute(
    `INSERT INTO settings (key, value) VALUES ($1, $2)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value`,
    [key, JSON.stringify(value)],
  );
}

export async function getAllSettings(): Promise<Record<string, unknown>> {
  const rows = (await getDb().select<{ key: string; value: string }[]>(
    "SELECT key, value FROM settings",
  )) as unknown as Array<{ key: string; value: string }>;
  const out: Record<string, unknown> = {};
  for (const r of rows) {
    try {
      out[r.key] = JSON.parse(r.value);
    } catch {
      out[r.key] = r.value;
    }
  }
  return out;
}
